services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mcp
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - "5173:80"
    restart: unless-stopped

networks:
  default:
    driver: bridge
